### ISSUE TITLE
Minimal working XML generator

### ISSUE THREAD

**Issue by adamallo** [pbousquets/phyfum#8]
It should re-generate flipflopCenancestor.xml with user-specified output prefix _outputName_ (for the _outputName_.trees, _outputName_.log, and _outputName_.ops files), number of MCMC iterations, and sampling frequency

**Comment by adamallo** [comment]
This needs to be updated after #12 is done

**Comment by adamallo** [comment]
Add an initial population size parameter (with the current 1 as default)

**Comment by pbousquets** [comment]
Everything done for now. I'm closing this issue!
